# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main  # main 브랜치에 push될 때 실행

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Log in to AWS ECR
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Build and push Docker image
#         run: |
#           REPO_URI=108782075530.dkr.ecr.ap-northeast-2.amazonaws.com/msa-test1
#           IMAGE_TAG=$(git rev-parse --short HEAD)
#           docker build -t $REPO_URI:$IMAGE_TAG .
#           docker push $REPO_URI:$IMAGE_TAG

#       - name: Update Kubernetes manifests
#         run: |
#           sed -i "s|image: .*|image: $REPO_URI:$IMAGE_TAG|g" k8s/deployment.yaml
#           git config --global user.email "euntaek4187@users.noreply.github.com"
#           git config --global user.name "GitHub Actions"
#           git add k8s/deployment.yaml
#           git commit -m "Update image tag to $IMAGE_TAG"
#           git push
